### ISSUE TITLE
KeyError: "['TEAM_ID' 'CFID' 'CFPARAMS' 'TEAM_NAME'] not found in axis"

### ISSUE THREAD

**Issue by markesha513** [kyleskom/NBA-Machine-Learning-Sports-Betting#82] opened 2023-02-09 09:31 UTC
![image](https://user-images.githubusercontent.com/124875975/217772817-6acb1124-fd27-4e49-914d-e13cb5bf6273.png)

Seems like he cant create result using data, try to update but dont see any fix. Yesterday all was working,

**Comment by Bejkerr** [comment] 2023-02-09 11:20
Same here

**Comment by cskerritt** [comment] 2023-02-09 13:14
Also having this issue

**Comment by vukjure** [comment] 2023-02-09 13:16
you can do a temporary quick fix in the main.py file:

change this line (line 52)
`frame_ml = games_data_frame.drop(columns=['TEAM_ID', 'CFID', 'CFPARAMS', 'TEAM_NAME'])`

to
```
columns_to_drop = ['TEAM_ID', 'CFID', 'CFPARAMS', 'TEAM_NAME']
existing_columns = games_data_frame.columns
columns_to_drop = list(set(columns_to_drop).intersection(existing_columns))
frame_ml = games_data_frame.drop(columns=columns_to_drop)
```

**Comment by cskerritt** [comment] 2023-02-09 13:23
> 

Excellent thank you!

**Comment by nickmalbsn** [comment] 2023-02-09 15:31
im getting this error now

  File "main.py", line 56
    data = frame_ml.values
    ^
IndentationError: unexpected indent

**Comment by Skysafe64** [comment] 2023-02-09 17:50
> im getting this error now
> 
> File "main.py", line 56 data = frame_ml.values ^ IndentationError: unexpected indent

The error "IndentationError: unexpected indent" means that you have incorrect indentation in your code. In Python, indentation is used to define the scope of a statement, so incorrect indentation can result in a syntax error.

To resolve this issue, make sure that all statements that belong to the same block are aligned correctly. Also, check that you are using the same number of spaces for the indentation of each code block in your file.

In general, in Python it is recommended to use 4 spaces for the indentation of each level. It is also important not to use both spaces and tabs for indentation. It is better to choose one of the two and stick to it.

**Comment by kyleskom** [comment] 2023-02-09 19:16
Duplicate of #84

**Closed by kyleskom** 2023-02-09 19:16 UTC
