### ISSUE TITLE
Google Colab

### ISSUE THREAD

**Issue by borgilkh** [kyleskom/NBA-Machine-Learning-Sports-Betting#83] opened 2023-02-09 12:07 UTC
File "main.py", line 106, in <module>
    main()
  File "main.py", line 79, in main
    data, todays_games_uo, frame_ml, home_team_odds, away_team_odds = createTodaysGames(games, df, odds)
  File "main.py", line 52, in createTodaysGames
    frame_ml = games_data_frame.drop(columns=['TEAM_ID', 'CFID', 'CFPARAMS', 'TEAM_NAME'])
  File "/usr/local/lib/python3.8/dist-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/frame.py", line 4906, in drop
    return super().drop(
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/generic.py", line 4150, in drop
    obj = obj._drop_axis(labels, axis, level=level, errors=errors)
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/generic.py", line 4214, in _drop_axis
    raise KeyError(f"{labels} not found in axis")
KeyError: "['TEAM_ID' 'CFID' 'CFPARAMS' 'TEAM_NAME'] not found in axis"

**Comment by HENN3SSEY** [comment] 2023-02-09 14:08
How did you fix this? I am still getting this same error.

**Comment by ntgale1984** [comment] 2023-02-09 15:00
Same issue. How to fix?

> Fixed it. Thanks

**Comment by kyleskom** [comment] 2023-02-09 19:16
Duplicate of #84

**Closed by kyleskom** 2023-02-09 19:16 UTC
