### ISSUE TITLE
Error when trying to run it in Google Colab

### ISSUE THREAD

**Issue by r12habh** [kyleskom/NBA-Machine-Learning-Sports-Betting#111] opened 2023-02-21 19:55 UTC
!python3 main.py -A -odds=fanduel

```
2023-02-21 19:26:47.784350: E tensorflow/stream_executor/cuda/cuda_driver.cc:271] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
2023-02-21 19:26:47.784421: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (db664a789cc2): /proc/driver/nvidia/version does not exist
2023-02-21 19:26:47.784875: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
Traceback (most recent call last):
  File "main.py", line 5, in <module>
    from src.Predict import NN_Runner, XGBoost_Runner
  File "/content/src/Predict/NN_Runner.py", line 10, in <module>
    model = load_model('Models/NN_Models/Trained-Model-ML')
  File "/usr/local/lib/python3.8/dist-packages/keras/saving/save.py", line 205, in load_model
    return saved_model_load.load(filepath, compile, options)
  File "/usr/local/lib/python3.8/dist-packages/keras/saving/saved_model/load.py", line 155, in load
    model.compile(**saving_utils.compile_args_from_training_config(
  File "/usr/local/lib/python3.8/dist-packages/keras/saving/saving_utils.py", line 202, in compile_args_from_training_config
    optimizer = optimizers.deserialize(optimizer_config)
  File "/usr/local/lib/python3.8/dist-packages/keras/optimizers.py", line 95, in deserialize
    return deserialize_keras_object(
  File "/usr/local/lib/python3.8/dist-packages/keras/utils/generic_utils.py", line 659, in deserialize_keras_object
    (cls, cls_config) = class_and_config_for_serialized_keras_object(
  File "/usr/local/lib/python3.8/dist-packages/keras/utils/generic_utils.py", line 556, in class_and_config_for_serialized_keras_object
    raise ValueError(
ValueError: Unknown optimizer: Custom>Adam. Please ensure this object is passed to the `custom_objects` argument. See https://www.tensorflow.org/guide/keras/save_and_serialize#registering_the_custom_object for details.

**Comment by nkgilley** [comment] 2023-02-21 21:04
duplicate of #110 , fixed in #109

**Comment by r12habh** [comment] 2023-02-21 21:30
@nkgilley 
Tried the code its working without errors, but whats this no games found thing
```
* x86train
2023-02-21 21:16:24.404515: E tensorflow/stream_executor/cuda/cuda_driver.cc:271] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
2023-02-21 21:16:24.404592: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (ff04d7bd6caf): /proc/driver/nvidia/version does not exist
2023-02-21 21:16:24.406848: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
No games found.

**Comment by nkgilley** [comment] 2023-02-21 21:51
There are no nba games today.

**Comment by r12habh** [comment] 2023-02-21 23:15
@nkgilley Can we add anyother games to this repo?
If yes, where should I start to explore the code.

**Closed** 2023-04-22 01:26 UTC
