### ISSUE TITLE
Incorrect Totals with sbrscrape

### ISSUE THREAD

**Issue by jnish23** [kyleskom/NBA-Machine-Learning-Sports-Betting#360] opened 2023-11-16 01:18 UTC
I've been noticing that sbrscrape gives incorrect totals for certain games. I haven't explored this in detail and will when I have more time. It appears certain games get mixed up.

For example on 11/12/2023:

![image](https://github.com/kyleskom/NBA-Machine-Learning-Sports-Betting/assets/58264256/7a2e9094-e404-43f2-b8c4-ea6bd606b3c6)

![image](https://github.com/kyleskom/NBA-Machine-Learning-Sports-Betting/assets/58264256/bbc40e9a-0022-48a6-b53c-5867af227144)

For example here I believe it mixed up the DAL @ NOP with DET @ Chicago. The scraper gives: 
Chicago Bulls (54.2%) vs Detroit Pistons: OVER 234.5 (67.3%)
New Orleans Pelicans vs Dallas Mavericks (59.4%): OVER 217 (67.1%)

On SportsBookReview you can see it's switched (and the lines moved a bit): 
Detroit Pistons @ Chicago OU 219.5
Dallas @ New Orleans OU 237

Not sure how often it happens, but I've noticed it more than a few times. It might be happening to a couple games a day. 
I opened an issue on the sbrscrape project but I'm not sure if its monitored anymore so just wanted to bring it to peoples' attention here.

**Comment by magic8bull** [comment] 2023-11-17 13:56
believe this the same issue as #328.  I've been trying to track this down since the results are completely wrong a lot of the time and landed here - https://github.com/nkgilley/sbrscrape/issues/4

I think the issue is related to the sbrscrape making multiple calls to SBR and assuming the results are returned in the same order for the ML, Odds, etc.  But they aren't.  Even if you review the webpage they sometimes come back in a different order.  Could be wrong but it seems the issue is with the scrape, not upstream.

**Comment by nkgilley** [comment] 2023-11-17 15:50
I was able to reproduce this today.  Try reverting to 0.0.4.  I'll have to take a closer look when I have time.

```
pip install -U sbrscrape==0.0.4
```

**Comment by nkgilley** [comment] 2023-11-17 16:41
Please test the fix in #362

**Closed** 2023-11-17 19:43 UTC
