### ISSUE TITLE
I have the same issue when using fanduel or any other. But it first worked, then after some time it stopped working and the error came.

### ISSUE THREAD

**Issue by Nightwarrior87** [kyleskom/NBA-Machine-Learning-Sports-Betting#61] opened 2023-01-26 02:14 UTC
I have the same issue when using fanduel or any other. But it first worked, then after some time it stopped working and the error came.
I run this: `!python3 main.py -A -odds=fanduel`
It was working hours ago. I got results and everything was fine. I have changed nothing and then this error appeared after trying to make the call again:
Traceback (most recent call last):
  File "main.py", line 104, in <module>
    main()
  File "main.py", line 66, in main
    odds = SbrOddsProvider(sportsbook=args.odds).get_odds()
  File "/content/src/DataProviders/SbrOddsProvider.py", line 30, in get_odds
    money_line_home_value = game['home_ml'][self.sportsbook]
KeyError: 'fanduel'

Same problem with all args

**Comment by kyleskom** [comment] 2023-01-26 02:33
Duplicate of #58

**Closed by kyleskom** 2023-01-26 02:33 UTC
